name: GTAWantedDisplayTestPlugin
version: ${project.version}
main: net.kunmc.lab.gtawanteddisplaystarplugin.GTAWantedDisplayStarPlugin
api-version: 1.15
commands:
  setstar:
    usage: /<Command> <NowWanted:int> <MaxWanted:int> <点滅:boolean>
