name: GTAWantedDisplayTestPlugin
version: ${project.version}
main: net.kunmc.lab.gtawanteddisplaytestplugin.GTAWantedDisplayTestPlugin
api-version: 1.15
commands:
  wanted:
    usage: /<Command> <MaxWanted:int> <NowWanted:double>
